[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bike_sim"
authors = [{name = "Dalton Luce", email = "dcl252@cornell.edu"}]
dynamic = ["version", "description"]
